# Generated by Django 3.2.6 on 2021-08-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
