# Generated by Django 3.2.6 on 2021-08-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210828_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='lng',
        ),
    ]
