# Generated by Django 3.2.6 on 2021-09-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210828_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
