# Generated by Django 3.1.2 on 2021-09-15 16:08

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210915_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
    ]
