# Generated by Django 3.1.2 on 2021-09-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bodega',
            new_name='Almacen',
        ),
    ]
