# Generated by Django 3.1.2 on 2021-09-15 22:20

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210915_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name='TiendaPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
