# Generated by Django 3.1.2 on 2021-09-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210915_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenpoint',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='polygonlayer',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tiendapoint',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
