# Generated by Django 3.1.2 on 2021-09-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210915_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenpoint',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='polygonlayer',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='tiendapoint',
            name='tipo',
        ),
        migrations.AddField(
            model_name='almacenpoint',
            name='markermodel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tiendapoint',
            name='markermodel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
