# Generated by Django 3.1.2 on 2021-09-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210915_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Almacen',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
